# Generated by Django 2.2.5 on 2019-10-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaga_cargo', models.CharField(max_length=40, verbose_name='Cargo da vaga')),
                ('vaga_descricao', models.TextField(max_length=250, verbose_name='Descrição da vaga')),
                ('vaga_salario', models.FloatField(verbose_name='Salário da vaga')),
                ('nome_categoria', models.CharField(
                    choices=[('TECH', 'Tecnologia'), ('ADV', 'Advocacia'), ('ENG', 'Engenharia'), ('MKT', 'Marketing')],
                    max_length=30, null=True, verbose_name='Categoria da vaga')),
                ('nome_tipo_inclusao', models.CharField(
                    choices=[('AllIn', 'AllIn'), ('BayAfro', 'BayAfro'), ('LGBTQ+', 'LGBTQ+'), ('Enable', 'Enable')],
                    max_length=30, verbose_name='Tipo inclusão')),
                ('vaga_status',
                 models.IntegerField(choices=[(1, 'Ativa'), (0, 'Desativada')], verbose_name='Status da vaga')),
            ],
        ),
    ]
